
logging.level:
  root: INFO
  com.example.lab02.service: DEBUG
  com.example.lab02.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR

server:
  port: 7071

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true
    enable:
      root: false
      jvm: true
      
opentracing:
  jaeger:
#    probabilistic-sampler.sampling-rate: 1.0
    serviceName: lab02
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
#    udp-sender:
#      host: jaeger-agent.istio-system.svc.cluster.local
#      port: 6831



lab02:
  cache:
    host: cache
    port: 6379
    enableSsl: false
    password: password
  event:
    host: bus
    port: 5672
    username: rabbitmq
    password: rabbitmq
