

mockserver.port: 7070

logging.level:
  root: INFO
  com.example.lab01.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR


opentracing:
  jaeger:
    serviceName: lab06BusCtaAho.default
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
#    udp-sender:
#      host: jaeger-agent.istio-system.svc.cluster.local
#      port: 6831



server:
  port: 8080
