
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true
    enable:
      root: false
      jvm: true
      
opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
    udp-sender:
      host: jaeger-collector.istio-system.svc.cluster.local
      port: 6831
      
        
server:
  port: 9999
  
