



logging.level:
  root: INFO
  com.example.lab01.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  io.opentracing.contrib: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true
    enable:
      root: false
      jvm: true

opentracing:
  jaeger:
#    probabilistic-sampler.sampling-rate: 1.0
    serviceName: lab06
    enabled: true
    enable-b3-propagation: true
    log-spans: true
    const-sampler:
      decision: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
#    udp-sender:
#      host: jaeger-agent.istio-system.svc.cluster.local
#      port: 6831





server:
  port: 7070


lab01:
  features:
    crypto.key: 123456789012345678901234567890
    panicEnabled: false
    ctaCteApi:
      url: http://lab06apictactevs.default.svc.cluster.local:7070/accounts
    ctaAhoApi:
      url: http://lab06apictaahovs.default.svc.cluster.local:7070/accounts
